### PR TITLE
Bump OpenBSD to 7.2.

### PR DESCRIPTION
**Pull request by xiaq**

### CODE REVIEW

**Comment by anarazel** [comment]
Feel free to merge - but wait for https://cirrus-ci.com/build/5504655504441344 to finish

**Review by anarazel — CHANGES_REQUESTED** [review]
Hm, the tests don't actually build the image, because we don't reference the pkrvars files in .cirrus.yml. @nbyavuz could you fix that?

**Review by anarazel — APPROVED** [review]
The pkrvars issue is resolved via #38, tests are running - I don't expect problems.

**Comment by xiaq** [comment]
Ping - can this be merged now?

**Comment by nbyavuz** [comment]
Merged, thanks @xiaq!

**Pull request merged**
